name: Pull Request Tests
run-name: PR check
on:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      pull-requests: write
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: 'true'

      # - name: Eco CI Energy Estimation - Initialize
      #   uses: green-coding-berlin/eco-ci-energy-estimation@v2
      #   with:
      #     task: start-measurement

      - name: 'Setup, Run, and Teardown Tests'
        uses: ./.github/actions/gmt-pytest
        with:
         metrics-to-turn-off: '--categories RAPL Machine Sensors Debug CGroupV2 MacOS'
         github-token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Eco CI Energy Estimation - Get Measurement
      #   uses: green-coding-berlin/eco-ci-energy-estimation@v2
      #   with:
      #     task: get-measurement
      #     branch: main

      # - name: Eco CI Energy Estimation - End Measurement
      #   uses: green-coding-berlin/eco-ci-energy-estimation@v2
      #   with:
      #     task: display-results
      #     branch: main
      #     pr-comment: true
        