name: Pull Request Tests
run-name: PR check
on:
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          submodules: 'true'

      - name: Eco CI Energy Estimation - Initialize
        uses: green-coding-berlin/eco-ci-energy-estimation@v1
        with:
          task: start-measurement

      - name: 'Setup, Run, and Teardown Tests'
        uses: ./.github/actions/gmt-pytest
        with:
         metrics-to-turn-off: '--categories RAPL System Sensors Debug CGroupV2 MacOS --providers CpuFrequencySysfsCoreProvider'
         github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Eco CI Energy Estimation - Get Measurement
        uses: green-coding-berlin/eco-ci-energy-estimation@v1
        with:
          task: get-measurement
          branch: dev

      - name: Eco CI Energy Estimation - End Measurement
        uses: green-coding-berlin/eco-ci-energy-estimation@v1
        with:
          task: display-results
          branch: dev
        


