name: Testing for @testing eco-ci-energy-estimation. Custom. No cron
run-name: Testing run for @testing eco-ci-energy-estimation
on:
  workflow_dispatch:

jobs:
  run-tests-main:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
      contents: read
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          ref: 'main'
          submodules: 'true'

      - name: Eco CI Energy Estimation - Initialize
        uses: green-coding-solutions/eco-ci-energy-estimation@testing
        with:
          task: start-measurement
          project: "Green Metrics Tool"
          machine: "ubuntu-latest"
          tags: "CI/CD, Test-Eco-CI-Workflow"
          gmt-api-token: ${{ secrets.GMT_API_TOKEN }}
          electricitymaps-api-token: ${{ secrets.ELECTRICITYMAPS_TOKEN }}


      - name: Measuring idle cost 10 s
        shell: bash
        run: |
            sleep 10

      - if: ${{ github.event_name == 'workflow_dispatch' || steps.check-date.outputs.should_run == 'true'}}
        name: 'Setup, Run, and Teardown Tests'
        uses: ./.github/actions/gmt-pytest
        with:
         github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Eco CI Energy Estimation - Get Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@testing
        with:
          task: get-measurement

      - name: Eco CI Energy Estimation - End Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@testing
        with:
          task: display-results
