name: Daily Test Run - Virtual Machine - Main Branch
run-name: Scheduled - main branch
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-tests-main:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - id: check-date
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: green-coding-berlin/eco-ci-activity-checker@v1
        with:
          branch: 'main'

      - if: ${{ github.event_name == 'workflow_dispatch' || steps.check-date.outputs.should_run == 'true'}}
        name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          ref: 'main'
          submodules: 'true'

      - name: Eco CI Energy Estimation - Initialize
        uses: green-coding-berlin/eco-ci-energy-estimation@v2
        with:
          task: start-measurement

      - if: ${{ github.event_name == 'workflow_dispatch' || steps.check-date.outputs.should_run == 'true'}}
        name: 'Setup, Run, and Teardown Tests'
        uses: ./.github/actions/gmt-pytest
        with:
         metrics-to-turn-off: '--categories RAPL Machine Sensors Debug CGroupV2 MacOS'
         github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Eco CI Energy Estimation - Get Measurement
        uses: green-coding-berlin/eco-ci-energy-estimation@v2
        with:
          task: get-measurement
          branch: main

      - name: Eco CI Energy Estimation - End Measurement
        uses: green-coding-berlin/eco-ci-energy-estimation@v2
        with:
          task: display-results
          branch: main
