name: Daily Test Run - Virtual Machine - Dev Branch
run-name: Scheduled - DEV Branch
on:
  schedule:
    - cron: '0 0 * * *'
  #push:
  #  branch: tests-minor-cleanups

jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      recent_dev_commit: ${{ steps.check_dev_commits.outputs.recent_commit }}
    steps:
      - id: check_dev_commits
        uses: green-coding-berlin/eco-ci-activity-checker@main
        with:
         repo: 'green-coding-berlin/green-metrics-tool'
         branch: 'dev'

  run-tests-dev:
    needs: check_date
    if: ${{ needs.check_date.outputs.recent_dev_commit == 'true' }}
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: 'dev'
          submodules: 'true'
      
      - name: 'Setup, Run, and Teardown Tests'
        uses: ./.github/actions/gmt-pytest
        with:
           metrics-to-turn-off: 'RAPL System Sensors Debug CGroupV2'
